### ISSUE TITLE
Get odo tests as part of OpenShift testgrid

### ISSUE THREAD

**Issue by mohammedzee1000** [redhat-developer/odo#1167]
[kind/Feature]

## Which functionality do you think we should add?

As odo is an OpenShift tool, it would be nice to get odo tested, as part of OpenShift's own tests. This means that whenever tests run for OpenShift, odo should get validated for it as well.

### Refer Links

Kubernetes Prow: https://github.com/kubernetes/test-infra
Kubernetes Test Grid: https://k8s-testgrid.appspot.com/
Kubernetes Gubernator:  https://gubernator.k8s.io/
Kubernetes Test Triage: https://storage.googleapis.com/k8s-gubernator/triage/index.html
OpenShift Gubernator: https://openshift-gce-devel.appspot.com/

Adding Jobs to prow: https://github.com/kubernetes/test-infra/blob/master/prow/jobs.md

## Why is this needed?

This will enable us to:

- Constantly be up-to date with latest OpenShift releases. When odo is part of OpenShift own testing, we will become aware of new versions very quickly, and also of any breakages, early on in the cycle
- We will be able to communicate more directly with the `OpenShift` team about odo.
- It will help us with continuous delivery of odo with OpenShift
- It will get us better visibility with little cost. We can leverage amazing test infrastructure developed for testing Kubernetes and OpenShift, without having to put the effort

## Tasks
 
- [x]  ~~Create a pre-test script that can bring fresh cluster upto speed with basic expectations of test, such as a user currently being logged in, and authorisation being setup for the users being used for the tests~~ Let's start with just building odo and running unit tests. Those won't have any dependency on OpenShift cluster.

- [x] Get a token for accessing OpenShift CI from OpenShift CI Administrators https://mojo.redhat.com/docs/DOC-1177573

- [x] Setup webhook, to hit https://hook-ci.svc.ci.openshift.org/hook with following parameters : 
  -  Content Type  : `application/json`
  - Secret : `token retrieved from above`
  - SSL verification : enabled
  - Event types : all
  - Active : yes

- [x] Grant the Team OpenShift Robots team write access to the repository. Since we are currently not in OpenShift Organization
  - [x] Invite `openshift-ci-robot` and `openshift-merge-robot` to org or add them as collaborators
  - [x] Contact one of CI administrators to accept invite, as needed
  - [x] Grant robots write access to repository

- [x] Configure prow as per our requirements
  - [x] Decide which plugins we want to use from list available https://deck-ci.svc.ci.openshift.org/plugins
  - [x] Update [openshift/release](https://github.com/openshift/release) making following changes
    - [x] [plugins.yaml](https://github.com/openshift/release/blob/master/cluster/ci/config/prow/plugins.yaml) to enable CI interacts against repository for plugins under `redhat-developer/odo` ie `$ord/$repo`
    -  [x] [config.yaml](https://github.com/openshift/release/blob/master/cluster/ci/config/prow/config.yaml) to
        - [x] Enable tide merge automation on repository
    - [x] Setup CI Operator by creating appropriate files in [ci-operator directory](https://github.com/openshift/release/tree/master/ci-operator)
        - [x] `ci-operator/config/redhat-developer/odo/redhat-developer-odo-master.yaml` (ci-operator/config/$org/$repo/$org-$repo-$branch.yaml) to 
            - [x]  Define release artifacts
            - [x]  Configure ci-operator test definitions for repository
        - [x] `ci-operator/jobs/redhat-developer/odo/redhat-developer-odo-master-$jobtype.yaml` to  to add test entries for Prow for repository [jobtype = presubmit, postsubmit, periodic]
        - [x] Add ourselves to `ci-operator/config/redhat-developer/odo/OWNERS` and `ci-operator/jobs/redhat-developer/odo/OWNERS`

**Comment by mohammedzee1000** [comment]
Depends on https://github.com/redhat-developer/odo/issues/1164

**Comment by amitkrout** [comment]
Cool stuff !!!

**Comment by mohammedzee1000** [comment]
@stevekuznetsov what would be your thoughts on this? This is being discussed  but i would love to know how possible is this and who would i have to talk to for more information?

**Comment by stevekuznetsov** [comment]
Totally. We have [this doc](https://docs.google.com/document/d/1SQ_qlkcplqhe8h6ONXdgBr7YUVbs4oRSj4ISl3gpLW4/edit#) that tries to lay out onboarding info

**Comment by mohammedzee1000** [comment]
@stevekuznetsov thanks. Sorry was in f2f. Going through the doc. This looks pretty dope.
One thing i did not find in the doc though is against what environments do the tests get run. It it just linux or other target platforms also included?

**Comment by stevekuznetsov** [comment]
Tests are scheduled as `Pod`s on an OpenShift cluster, which is running linux x86.

**Comment by stevekuznetsov** [comment]
You can choose your distro by choosing a different image for the container, of course.

**Comment by amitkrout** [comment]
@kadel This need more exploration and time investment. Due to less band width we could not spend much time on it. Later will talk to @mohammedzee1000 to plan it further

**Comment by mohammedzee1000** [comment]
@kadel @amitkrout  Yes, this will require a little bit more preparation. Our current tests are very tied to minishift, with bringing up the cluster being part of the test. 

We need to note here that OpenShift is the dependency, not Minishift, which just brings up the cluster.

As stated above by @stevekuznetsov, we will get a ready made full fledged cluster on OpenShift, which means certain assumptions made on Minishift will no longer hold true, for example the developer user may not exist and certain configs done by minishift for ease of developer may not hold true, and we may need to add steps into BeforeSuite to handle this. 

@amitkrout may be able to point out more such assumptions that will no longer work without additional setup as he was in Minishift for some time now.

**Comment by mohammedzee1000** [comment]
@kadel @amitkrout updated tentative task list, PTAL

**Comment by mohammedzee1000** [comment]
@stevekuznetsov hope i did not miss anything?

**Comment by mohammedzee1000** [comment]
Email conversation started for acquiring token

**Comment by stevekuznetsov** [comment]
Yep! that seems correct

**Comment by mohammedzee1000** [comment]
Configuration creation wip in https://github.com/mohammedzee1000/openshift-release/tree/redhatdeveloper-odo-prow-init

**Comment by mohammedzee1000** [comment]
Webhook and robot access is complete

**Comment by kadel** [comment]
I think that we can close this issue. CI setup is completed and we have first tests running there.


Issue tracking progress of moving tests: https://github.com/redhat-developer/odo/issues/1431

**Comment by mohammedzee1000** [comment]
Makes sense. Closiing
/close
