### ISSUE TITLE
UC 10: As a developer, I want to get a full description of my application and components

### ISSUE THREAD

**Issue by jorgemoralespou** [redhat-developer/odo#155]
As a developer, I want to be able to get a full description of my application and what components constitutes my application including storage, URLs, etc.

```
$ ocd app describe [--app=name]
Application XYZ has:
Component ABC with source in https://git and scaled to 2 instances, exposed via http://blabla and connected to component DB1, and component DB2
Component DB1, based of PostgreSQL and scaled to 1 connected by Component ABC
Component DB2, based of MongoDB and scaled to 1 connected by Component ABC
------------
$ ocd describe [name]
Component ABC with source in https://git and scaled to 2 instances, exposed via http://blabla and connected to component DB1, and component DB2
Application context
Parameters were …
Env vars ...
```

- [x]  #196 Get full description of a component

- [x]  #197 Get a full description of my application
- [ ] #199 Get full description of what is part of a component given as argument

- [ ]  #198 Get a full description of an application provided

**Comment by cdrage** [comment]
@jorgemoralespou has our `odo describe` implementation fulfilled this requirement?

**Comment by jorgemoralespou** [comment]
The information it provides is too scarce. We need to define what needs to be shown. As can be seen in #196 and #197 and in the description of this issue.

e.g.:
```
odo app describe
Application wwgame has:
Component backend of type wildfly with source in file:///Users/jmorales/repositories/jorgemoralespou/openshift-evangelists/WW-Game/Wild-West-Backend/target/ROOT.war
Component frontend of type nodejs with source in file:///Users/jmorales/repositories/jorgemoralespou/openshift-evangelists/WW-Game/Wild-West-Frontend
Externally exposed via frontend-wwgame-odo-demo.apps.osevg.openshiftworkshop.com
```

We should probably need to have a `--full` or `--short` flags that show more detail/concise output. What do you think, @kadel.
