### ISSUE TITLE
UC 15: As a developer, I want to sync my local source code changes to an existing component of my application.

### ISSUE THREAD

**Issue by jorgemoralespou** [redhat-developer/odo#160]
As a developer, I want a quick and convenient way for using openshift as a true development platform.  I want to be able to code locally and have it sync my changes to my running component and be smart enough to let me know when a restart of the container is required if dependencies have changed.  This should work across PHP, Node.JS, Python, Ruby, and Java.

```
$ cd myfrontend
$ ocd create php:5.4
$ ocd push
$ ocd watch [.]  //blocks terminal and watches for file changes

Output:
Watching for changes.  To stop, use control-c
[11:34:12] myfile.php was pushed
[12:04:05] logo.png was pushed
------
$ cd myfrontend
$ ocd create wildfly --binary=target/my-app.war
$ ocd push
$ ocd watch [--binary=target/mybetterapp.war]
                                         ^ override
Output:
Watching for changes on target/my-app.war.  To stop, use control-c
[13:45:10] target/myapp.war was pushed
[14:05:32] target/myapp.war was pushed
```

__*NOTE:*__ Check the following blog posts for examples:
- [Interpreted languages](https://blog.openshift.com/instant-developer-gratification-with-php-and-docker-based-containers/)
- [Java](https://blog.openshift.com/fast-iterative-java-development-on-openshift-kubernetes-using-rsync/)

Default configuration should be to sync based on how the component is configured.
- If the component is local, sync current directory (excluding .git, possibly others)
- If the component is binary, watch and sync the binary
- If a flag (override) is passed as argument, use that one as watch and sync pattern.

Tasks (create new issues if deferring some work):
- [x] #207 Provide a way to sync local directory
- [x] #208 Provide a flag to specify to watch and sync a file
- [ ] Provide a flag to specify to watch and sync a directory

**Comment by kadel** [comment]
We should have at least basic implementation of this for MVP (hacking it is OK). 
Stretch goal for MVP

**Comment by cdrage** [comment]
Watch / push has been implemented and you're able to sync with your local directory.

Closing this!
