### ISSUE TITLE
UC 17: As a developer, I want to change the source of my component to be a remote git repository and back to local or vice versa (remote to local)

### ISSUE THREAD

**Issue by jorgemoralespou** [redhat-developer/odo#162]
As a developer I want to be able to change the source of a component from local (source or binary being pushed) to remote (git) so that it can be built by the system in an unattended way. 

```
$ ocd create php [myfrontend]
<Code for a while>
$ ocd push
<Code for a while>
git init
git remote add github.comafjdalkjfa
git push
$ ocd update [myfrontend] --git=<url>
$ ocd update [myfrontend] --local
$ ocd update [myfrontend] --binary=target/myfrontend.war
```

Dependency on #165 

Tasks (Should create sub issues is work is deferred):
- [ ] #209 Change to use Git as source for the build
- [ ] #210 Change the build to use local directory as source
- [ ] #211 Change the build to use binary as source

**Comment by cdrage** [comment]
All three subtasks have been implemented #209 #210 #211 

I'm closing this.
