### ISSUE TITLE
UC 24: As a developer, I want to be able to push local directory contents or a binary artifact

### ISSUE THREAD

**Issue by jorgemoralespou** [redhat-developer/odo#169]
As a developer, I want to be able to push local directory contents or an artifact, if I have built a binary artifact that can be directly pushed. The push commands will default to push contents of the local directory, but with a flag the behaviour changes to push a binary artifact.

```
$ cd mydir
$ ocd create wildfly 
$ ocd push (This will push the local directory to be built on the server)
----------------
$ cd mydir
$ ocd create wildfly --git=<something>
$ ocd push
---------------
$ cd mydir
$ ocd create wildfly --binary=target/my-file.war
$ mvn clean package 
$ ocd push 
---------------
$ cd mydir
$ ocd create wildfly --binary=target/my-file.war
$ ocd push 
Error: target/my-file.war can not be found
---------------
$ cd mydir
$ ocd create wildfly --binary=target/my-file.war
$ ocd push --binary=target/my-file2.war  (OVERRIDE)
```

When creating a component one can specify how the source will be provided to it, if a built (s2i) component.
Possible options are:
- local (local directory will be passed. This should be the default if nothing is specified)
- binary=[BINARY_LOCATION] file provided as argument will be passed
- git=[GIT URL] A git repo will be used for the build

Tasks (need issues if work is deferred):
- [x] #221 Configure the build to use local directory
- [x] #219 Configure the build to use a binary file
- [x] #220 Configure the build to use a git repository
- [x] #222 Push contents (start the build)

Documentation related to this feature: 
- https://docs.openshift.org/latest/dev_guide/dev_tutorials/binary_builds.html
- https://docs.openshift.org/latest/dev_guide/builds/build_inputs.html#binary-source

**Comment by kadel** [comment]
decompose this to smaller tasks.

**Comment by kadel** [comment]
@jorgemoralespou can you please give us more context, especially on `--binary`

**Comment by cdrage** [comment]
Do you think we can close this now @surajnarwade ?

**Comment by surajnarwade** [comment]
@cdrage , yes we can close this since we can now push `--binary` as well and even we are not dependent on `oc` either

Closing
