### ISSUE TITLE
Review JSON output for all odo commands

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#1739]
One more acceptance criteria would be to

- [ ] JSON Output for devfile needs to have long term design as we cannot break it after v2

- [ ] review existing commands as mentioned below

List of all commands that vscode adapter uses - https://github.com/redhat-developer/vscode-openshift-tools/blob/8b9baa56a77d02a54a37fd4532a3d1948ed53a01/src/odo.ts#L36

### listProjects
vscode plugin executes:  `oc get project -o jsonpath="{range .items[?(.status.phase == \\"Active\\" )]}{.metadata.name}{\\"\\n\\"}{end}"'`

`odo project list -o json`

*Note: (we don't need/have --project flag for odo project list )*

Question: do we need this flag to retrieve specific project (equivalent can be `odo project get`)

```json
{
    "kind": "List",
    "apiVersion": "odo.openshift.io/v1alpha1",
    "metadata": {},
    "items": [
        {
            "kind": "Project",
            "apiVersion": "odo.openshift.io/v1alpha1",
            "metadata": {
                "name": "myproject",
            },
            "spec": {
                "apps": [
                    "myapp",
                ]
            },
           "status": {
              "active": false
            }
        }
    ]
}
```
TODO: 
 - ~~remove `status.active` field~~ 

### listApplications
vscode plugin executes: `odo application list --project ${project} -o json`

```json
{
    "kind": "List",
    "apiVersion": "odo.openshift.io/v1alpha1",
    "items": [
        {
            "kind": "Application",
            "apiVersion": "odo.openshift.io/v1alpha1",
            "metadata": {
                "name": "app",
                "namespace": "myproject"
            },
            "spec": {
                "components": [
                    "java-jpxy",
                    "nodejs-ngrl",
                    "nodejs-yvnq"
                ]
            }
        }
    ]
}
```
TODO: 
 - remove `status.active` field 
- Issue: https://github.com/openshift/odo/issues/1866

### deleteProject
vscode plugin executes: `odo project delete ${name} -f`

`odo project delete ${name} -f -o json`
On success:
 - exitcode 0, and no other output on stdout or stderr.

On failure:
 - exitcode >0, json output on stderr
```json
{
    "kind": "Error",
    "apiVersion": "odo.openshift.io/v1alpha1",
    "metadata": {
        "namespace": "myproject",
    },
    "message": "Unable to delete project myproject"
}
```

TODO:
- Add `-o json` 

### waitForProjectToBeGone
vscode plugin executes: `oc wait project/${project} --for delete`

This command should not be needed, as `odo project delete` should wait for the project to be deleted.

TODO:

* implement `--wait` flag

### createProject
vscode plugin executes: `odo project create ${name}`

`odo project create ${name} -o json`
```json
{
    "kind": "Project",
    "apiVersion": "odo.openshift.io/v1alpha1",
    "metadata": {
        "name": "myproject",
        "namespace": "myproject",
    }
}
```

if error, return error exit code (>0) and stderr :
```json
{
    "kind": "Error",
    "apiVersion": "odo.openshift.io/v1alpha1",
    "metadata": {
        "namespace": "myproject",
    },
    "message": "Unable to create project myproject"
}
```

TODO:

* implement `-o json`

### listComponents
`odo list --app ${app} --project ${project} -o json`

STATUS: we already have this

### listCatalogComponents
`odo catalog list components`

STATUS: we already have this & we don't need json for this

### listCatalogServices
`odo catalog list services`

STATUS: we already have this & we don't need json for this

### listStorageNames
`odo storage list --app ${app} --project ${project} --component ${component} -o json`

### listServiceInstances:
`oc get ServiceInstance -o jsonpath="{range .items[?(.metadata.labels.app == \\"${app}\\")]}{.metadata.labels.app\\.kubernetes\\.io/component-name}{\\"\\n\\"}{end}" --namespace ${project}`

### createApplication
`odo app create ${app} --project ${project}`

###  describeApplication
`odo app describe ${app} --project ${project}`

STATUS: we already have this command and json output

### deleteApplication
`odo app delete ${app} --project ${project} -f`,

### createStorage
`odo storage create ${storageName} --path=${mountPath} --size=${storageSize} --project ${project} --app ${app} --component ${component}`

### deleteStorage
`odo storage delete ${storage} -f --project ${project} --app ${app} --component ${component}`

### waitForStorageToBeGone
`oc wait pvc/${storage}-${app}-pvc --for=delete --namespace ${project}`

### deleteComponent
`odo delete ${component} -f --app ${app} --project ${project}`

### describeComponent
`odo describe ${component} --app ${app} --project ${project}`

STATUS: we already have this command & json output

### describeService
`odo catalog describe service ${service}`

STATUS: we already have this command & we don't need json output for this

### showLog
`odo log ${component} --app ${app} --project ${project}`

STATUS: we already have this command & we don't need json output for this

### showLogAndFollow
`odo log ${component} -f --app ${app} --project ${project}`

STATUS: we already have this command & we don't need json output for this

### listComponentPorts
`oc get service ${component}-${app} --namespace ${project} -o jsonpath="{range .spec.ports[*]}{.port}{','}{end}"`

STATUS: I think https://github.com/openshift/odo/pull/1828 will solve this problem partially. as after this PR, `odo create` will get all the ports and put it in localconfig files, from their, vscode extensions can grab.

### linkComponentTo
`odo project set ${project} && odo application set ${app} && odo component set ${component} && odo link ${componentToLink} --wait${port ? ' --port ' + port : ''}`

### pushComponent
`odo push ${component} --app ${app} --project ${project}`

ALERT:

* we don't have `--app` and `--project` flag to `odo push` instead we have `--context` flag
 
### pushLocalComponent
`${Command.pushComponent(project, app, component)} --local ${location}`

### watchComponent
`odo watch ${component} --app ${app} --project ${project}`

STATUS: we already have this & we don't need json output for this

### getRouteHostName
`oc get route --namespace ${namespace} -o jsonpath="{range .items[?(.metadata.labels.app\\.kubernetes\\.io/component-name=='${component}')]}{.spec.host}{end}"`

TODO:

equivalent command should be `odo url list --component nodejs-zeaa --project myproject -q`

* here, we need to add `-q` flag which will return url

### createLocalComponent
`odo create ${type}:${version} ${name} --local ${folder} --app ${app} --project ${project}`

### createGitComponent
`odo create ${type}:${version} ${name} --git ${git} --ref ${ref} --app ${app} --project ${project}`

### createBinaryComponent
`odo create ${type}:${version} ${name} --binary ${binary} --app ${app} --project ${project}`

### createService
`odo service create ${template} --plan ${plan} ${name} --app ${app} --project ${project} -w`

### deleteService
`odo service delete ${name} -f --project ${project} --app ${app}`

### getServiceTemplate
`oc get ServiceInstance ${service} --namespace ${project} -o jsonpath="{$.metadata.labels.app\\.kubernetes\\.io/component-type}"`

### waitForServiceToBeGone
`oc wait ServiceInstance/${service} --for delete --namespace ${project}`

### createComponentCustomUrl
`odo url create ${name} --port ${port} --project ${project} --app ${app} --component ${component}`

STATUS: `odo url create` just modifies local config, so I think we don't need json output

### getComponentUrl
`odo url list --component ${component} --app ${app} --project ${project} -o json`

STATUS: we already have this

### getComponentJson
`oc get service ${component}-${app} --namespace ${project} -o json`

QUERY: why we need output of service ?

**Comment by surajnarwade** [comment]
> listProjects
> vscode plugin executes: oc get project -o jsonpath="{range .items[?(.status.phase == \\"Active\\" )]}{.metadata.name}{\\"\\n\\"}{end}"'
> 
> odo project list --project ${project} -o json

if we want single project json, we can use `odo project get`

**Comment by surajnarwade** [comment]
## Tracking

- [ ] listProjects
- [ ] listApplications
- [ ] deleteProject
- [ ] waitForProjectToBeGone
- [ ] createProject
- [ ] listComponents
- [ ] listCatalogComponents
- [ ] listCatalogServices
- [ ] listStorageNames
- [ ] listServiceInstances
- [ ] createApplication
- [ ] describeApplication
- [ ] deleteApplication
- [ ] createStorage
- [ ] deleteStorage
- [ ] waitForStorageToBeGone
- [ ] deleteComponent
- [ ] describeComponent
- [ ] describeService
- [ ] showLog
- [ ] showLogAndFollow
- [ ] listComponentPorts
- [ ] linkComponentTo
- [ ] pushComponent
- [ ] pushLocalComponent
- [ ] watchComponent
- [ ] getRouteHostName
- [ ] createLocalComponent
- [ ] createGitComponent
- [ ] createBinaryComponent
- [ ] createService
- [ ] deleteService
- [ ] getServiceTemplate
- [ ] waitForServiceToBeGone
- [ ] createComponentCustomUrl
- [ ] getComponentUrl
- [ ] getComponentJson

**Comment by cdrage** [comment]
### Charlie's list

- [x] listProjects
- [x] listApplications (see #1866 / @surajnarwade 's PR)
- [ ] deleteProject
- [ ] waitForProjectToBeGone
- [ ] createProject
- [ ] listComponents
- [ ] listCatalogComponents
- [ ] listCatalogServices
- [ ] listStorageNames
- [ ] listServiceInstances
- [ ] createApplication
- [ ] describeApplication
- [ ] deleteApplication
- [ ] createStorage
- [ ] deleteStorage
- [ ] waitForStorageToBeGone
- [ ] deleteComponent
- [ ] describeComponent
- [ ] describeService
- [ ] showLog
- [ ] showLogAndFollow
- [ ] listComponentPorts
- [ ] linkComponentTo
- [ ] pushComponent
- [ ] pushLocalComponent
- [ ] watchComponent
- [ ] getRouteHostName
- [ ] createLocalComponent
- [ ] createGitComponent
- [ ] createBinaryComponent
- [ ] createService
- [ ] deleteService
- [ ] getServiceTemplate
- [ ] waitForServiceToBeGone
- [ ] createComponentCustomUrl
- [ ] getComponentUrl
- [ ] getComponentJson

**Comment by kadel** [comment]
> ### listComponentPorts
> `oc get service ${component}-${app} --namespace ${project} -o jsonpath="{range .spec.ports[*]}{.port}{','}{end}"`
> 
> STATUS: I think #1828 will solve this problem partially. as after this PR, `odo create` will get all the ports and put it in localconfig files, from their, vscode extensions can grab.

odo will need command to display this information. The extensions should never read the localconfig files directly.
I think that `odo component describe` is a good place where this information should be shown

**Comment by kadel** [comment]
> ### getRouteHostName
> `oc get route --namespace ${namespace} -o jsonpath="{range .items[?(.metadata.labels.app\\.kubernetes\\.io/component-name=='${component}')]}{.spec.host}{end}"`
> 
> TODO:
> 
> equivalent command should be `odo url list --component nodejs-zeaa --project myproject -q`
> 
> * here, we need to add `-q` flag which will return url

`-q` won't be needed.
It should be possible to pick up the hostname from  `odo url list --component nodejs-zeaa --project myproject -o json` output

**Comment by cdrage** [comment]
Hey @dgolovin I'm going over `deleteProject` right now...

I was thinking of this in terms of implementation, or of course something similar, this is a super rough draft...

```json
    "kind": "Success",
    "apiVersion": "odo.openshift.io/v1alpha1",
    "metadata": {
        "namespace": "myproject",
    },
    "message": "Deleted foobar"
    "project": foobar,
}
```

Or is there something specific we should implement in a certain way?

**Comment by cdrage** [comment]
Update:

So currently I have to implement a few changes in order to correctly add creation / deletion json output for `odo project create/delete` commands. I just want to give a quick update to both @surajnarwade @tkral and @degolovi that in order to do so I have to:
 - Add a json global parameter so we can detect if we are indeed doing machine readable output. This would of been added anyways since we have to have json output for (almost) every command for odo
 - Change how logging works by detecting if we're using `-o json` and disabling ANY form of logging in order to prevent malformed json (normal output + json)

**Comment by kadel** [comment]
This issues is not valid anymore. With coming v3 the json output will have to be reworked in a completely different way.

**Comment by kadel** [comment]
This issues is not valid anymore. With coming v3 the json output will have to be reworked in a completely different way.

**Comment by kadel** [comment]
This issues is not valid anymore. With coming v3 the json output will have to be reworked in a completely different way.
