### ISSUE TITLE
Run e2e and integration test on windows and macOS host

### ISSUE THREAD

**Issue by prietyc123** [redhat-developer/odo#2540]
[kind/Feature]

## Which functionality do you think we should add?

We can borrow macOS host on travis and windows from appveyor then only we can start our tests on these hosts.

## Why is this needed?

Not yet implemented in CI.

 - [ ] Integration tests
     - [ ] Mac OS https://github.com/redhat-developer/odo/issues/5301
     - [x] Windows https://github.com/redhat-developer/odo/issues/5300
 - [ ] e2e tests
     - [ ] Mac OS https://github.com/redhat-developer/odo/issues/5301
     - [x] Windows https://github.com/redhat-developer/odo/issues/5300

**Comment by amitkrout** [comment]
@mohammedzee1000 Can we please add those inputs that we discussed yesterday and before. @prietyc123 FYI...

**Comment by mohammedzee1000** [comment]
We can use travis.rb which is the official cli for travis ci or we can directly use the API.

The main drawbacks of travis.rb is we cannot create job manually, just restarting existing ones and also while we can set envs, we cannot do it per build

So i propose:

- configure travis job which looks for env and if not present fails
- prow job starts and brings up cluster
- prow job passes on cluster url to travis job with env and restarts it

**Comment by mohammedzee1000** [comment]
https://github.com/travis-ci/travis.rb
The problematic bit where dirty reads can occur is https://github.com/travis-ci/travis.rb#env and we should plan around that.

For example after cluster is brought up, the prow job goes into a loop, where it injects env say `CLUSTER_URL=10;example.com` (where 10 is PR no) and restarts the job, then waits for build to become a success. If any builds fail then it restarts the same for say 3 times after which it is assumed as failed forever (basically full retrigger required).

Travis job on its part reads `CLUSTER_URL="10;example.com"` reads pr no and if it does not match, it fails. Otherwise, it reads the cluster URL and stores it in different env and resumes tests

@amitkrout @girishramnani  wdyt

**Comment by mohammedzee1000** [comment]
https://github.com/travis-ci/travis.rb/issues/717

**Comment by mohammedzee1000** [comment]
```
❯ travis env set FOO BAR
[+] setting environment variable $FOO
❯ travis env list
# environment variables for mohammedzee1000/odo
FOO=[secure]


```

**Comment by mohammedzee1000** [comment]
Steve said:
Prow provides these env vars, so you could get the PR number by:
pr_num="$( jq .refs.pulls[0].num <<<"${JOB_SPEC}" )" # recommended
pr_num="${PULL_NUMBER}" # may be deprecated
https://github.com/kubernetes/test-infra/blob/master/prow/jobs.md#job-environment-variables

**Comment by mohammedzee1000** [comment]
![image](https://user-images.githubusercontent.com/8547729/76322840-e0776d00-6309-11ea-9d50-1327e41501e5.png)

**Comment by kadel** [comment]
Would it be possible to run tests against some of the internal clusters (like `ocp311.odo`) instead of using OpenShift's Prow?

**Comment by mohammedzee1000** [comment]
That would depend on if we can get something that can talk to both sides, like a public Jenkins that can talk to internal resources, for instance

**Comment by mohammedzee1000** [comment]
It might be possible to use API v3 calls to set env for specific build. If we can get this information, we could potentially avoid the loops

**Comment by mohammedzee1000** [comment]
Note @amitkrout will be doing the work :)

**Comment by mohammedzee1000** [comment]
I feel short team we should start with travis + prow and then once we have 4x cluster and the Jenkins story figured out (optionally DNS as well) then we can move it all to PSI

**Comment by amitkrout** [comment]
TBH no major movement i did in the current sprint except playing around the travis cli just to figure out the pattern. 

The most important part currently i need to check is to figure out how we are going to get a github token/travis token into hands of prow. That is why i moved the state from ready to needs-information.

ping @mohammedzee1000

**Comment by mohammedzee1000** [comment]
For the token problem, we could do something of a hide in plain sight. This should not be used to often so should not need to be changed very often so we should discuss offline on how we do that, if we are. Otherwise we are going to have to wait on prow secrets to inject the token. 

We also know that bitwarden is used by openshift release as another way to hold secrets. Regardless, since this prow job won't run the actual tests, it should be ok to use the container job thing too. Need to discuss further with prow team

**Comment by amitkrout** [comment]
> For the token problem, we could do something of a hide in plain sight. This should not be used to often so should not need to be changed very often so we should discuss offline on how we do that, if we are. Otherwise we are going to have to wait on prow secrets to inject the token.
> 
> We also know that bitwarden is used by openshift release as another way to hold secrets. Regardless, since this prow job won't run the actual tests, it should be ok to use the container job thing too. Need to discuss further with prow team

@mohammedzee1000 Can you please summarize the tread discussion you had with prow team, so that team will come to know our next plan of action.

**Comment by mohammedzee1000** [comment]
Ok, we are in process of getting the `odo-bot` GitHub token injected into prow. The current method which is currently the only way is global ie all prow jobs.

Once it is in, we should be able to access it using `PULL_SECRET_PATH`. It will be json which will likely end up in the form of 

```
 "odo-bot": {
      "auth": "blablablabla"
    }
```

So we should be able to pull it with `jq`

Once we have the token, we login with travis cli, pull the builds based on PR no, and trigger/retrigger after setting travis env. 

Here is a script that I wrote that can already filter based on PR no

```bash
❯ cat test.sh
#!/usr/bin/env bash

if [[ -z $PR_NO ]]; then
	echo "Please set PR_NO"
	exit 1
fi

if [[ -z $GITHUB_TOKEN ]]; then
	echo "Please set GITHUB_TOKEN"
	exit 1
fi

REPO=openshift/odo

hist=`mktemp`
hist_nofirst=`mktemp`

# Travis login with token here
echo "Logging in to travis with provided token..."
travis login --github-token $GITHUB_TOKEN --com

# Get travis job history and store in in file after trunicating multiple spaces
# TODO: there is a way to filter history by PR NO in command but is currently broken https://github.com/travis-ci/travis.rb/issues/382
# Once it works we can avoid a bunch of this script
echo "Querying travis history..."
travis history --limit 100 -r $REPO | tr -s ' ' > $hist
# Cut away first column as its build no which follows same pattern as pr no so we can match pr no easily
echo "Cutting out first column as its pattern is similar to pr no"
cat $hist | cut -d ' ' -f1 --complement > $hist_nofirst
# get all line nos where pr no is present
echo "Getting all line numbers where the PR no $PR_NO occours"
line_nos=`grep -Fn $PR_NO $hist_nofirst | cut -d : -f1`
echo "Iterating over travis history to find all builds for pr"

for n in $line_nos; do
	build_no=`sed "${n}q;d" $hist | cut -d ' ' -f1`
	build_no="${build_no//#}"
	build_status=`sed "${n}q;d" $hist | cut -d ' ' -f2`
	build_status="${build_status//:}"
	if [[ ! -z $out ]];then
		out="$out "
	fi
	out="$out$build_no:$build_status"
done

echo $out

```

The output is:

```
❯ PR_NO=3129 GITHUB_TOKEN=<redacted> sh test.sh
Logging in to travis with provided token...
Successfully logged in as odo-bot!
Querying travis history...
Cutting out first column as its pattern is similar to pr no
Getting all line numbers where the PR no 3129 occours
Iterating over travis history to find all builds for pr
9602:passed 9601:failed 9549:passed

```

We should likely need to only work with latest build if it succeeds, then test succeeded else we set a travis env `travis env set foo bar --public` and then, depending on if restarts of jobs cause new env to be read (needs verification), either restart the latest build `travis restart 57` or `travis restart 57.x` or trigger a new one on the PR no (still need to figure out but hopefully wont need to go there).

**Comment by mohammedzee1000** [comment]
https://github.com/travis-ci/travis.rb/issues/382

**Comment by mohammedzee1000** [comment]
@amitkrout we should not need to give login information by the way just cluster url as everything else is fixed in tests

**Comment by mohammedzee1000** [comment]
Ok it appears that the `--pull-request` bug has been fixed in travis cli version `1.9.1`(https://rubygems.org/gems/travis/versions/1.9.1.travis.1219.9). This is however a prerelease ie `gem install travis --pre`.

If we are able to go ahead with this then the script can be cut short by a lot i.e

```
#!/usr/bin/env bash

if [[ -z $PR_NO ]]; then
	echo "Please set PR_NO"
	exit 1
fi

if [[ -z $GITHUB_TOKEN ]]; then
	echo "Please set GITHUB_TOKEN"
	exit 1
fi

REPO=openshift/odo

hist=`mktemp`

# Travis login with token here
echo "Logging in to travis with provided token..."
travis login --github-token $GITHUB_TOKEN --com

echo "Querying travis history..."
travis history --limit 15 -p $PR_NO -r $REPO --com | tr -s ' ' > $hist
echo "Iterating over travis history to find all builds for pr $PR_NO"
while IFS= read -r line
do
        build_no=echo $line | cut -d ' ' -f1`
        build_no="${build_no//#}"
        build_status=echo $line | cut -d ' ' -f2`
        build_status="${build_status//:}"
	if [[ ! -z $out ]];then
		out="$out "
	fi
	out="$out$build_no:$build_status"
done < "$hist"

echo $out

```

**Comment by amitkrout** [comment]
Blocked due to https://github.com/openshift/odo/issues/3270

**Comment by prietyc123** [comment]
> Blocked due to #3270

As we are now moved to multistage test infra you should be able to get the environment variable such as `PULL_SECRET_PATH` needed for this issue. Unblocking the issue.

**Comment by amitkrout** [comment]
https://github.com/openshift/odo/issues/2019 will be fixed as part of this issue.

**Comment by amitkrout** [comment]
Latest update on the issue - https://github.com/openshift/odo/issues/2540#issuecomment-618401118

**Comment by amitkrout** [comment]
> #2019 will be fixed as part of this issue.

https://github.com/openshift/odo/issues/2019#issuecomment-677883378

**Comment by amitkrout** [comment]
> > #2019 will be fixed as part of this issue.
> 
> [#2019 (comment)](https://github.com/openshift/odo/issues/2019#issuecomment-677883378)

#2019 has been fixed through https://github.com/openshift/release/pull/11166

**Comment by amitkrout** [comment]
Task list

- [ ] Create a prow job - openshift/release#10942
- [ ]  Install travis cli in the test container - #3732
- [ ]  Use github token to login into odo travis job
- [ ]  Pick the travis build number where we have mac and windows jobs are running
- [ ]  Trigger the travis job with the 4.* cluster login information

**Comment by prietyc123** [comment]
As we have already set up our periodic run on PSI. There is a similar plan for PR runs as well, but for this to get implemented we are first looking for our POC on fedora to get succeed as discussed in https://github.com/openshift/odo/issues/4056 . I will be working with @mohammedzee1000 on this.

**Comment by prietyc123** [comment]
We will wait on POC https://github.com/openshift/odo/issues/4056 outcome because we have similar plan for automation of e2e and integration tests on macOS and windows. So kind of blocked on the POC task

**Comment by kadel** [comment]
> We will wait on POC #4056 outcome because we have similar plan for automation of e2e and integration tests on macOS and windows. So kind of blocked on the POC task

@prietyc123 So plan is to run even Windows and MacOS e2e tests on PSI? I don't see anything about that in @mohammedzee1000 POC.

**Comment by prietyc123** [comment]
> > We will wait on POC #4056 outcome because we have similar plan for automation of e2e and integration tests on macOS and windows. So kind of blocked on the POC task
> 
> @prietyc123 So plan is to run even Windows and MacOS e2e tests on PSI? I don't see anything about that in @mohammedzee1000 POC.


We have already set up the multi platform machine on psi and there is one poc pr #4063 in WIP . So we will also follow similar flow for other platforms as well. @mohammedzee1000 it would be great if you can share your inputs on merge duration for pr #4063 because I am not sure whether we are in a place to jump on implementing this scenario currently with other platforms like windows and macOS.

**Comment by dharmit** [comment]
@mohammedzee1000 how long do you think before get #4063 in? Only then we can start working on this, right?

**Comment by rm3l** [comment]
Closing this.

Related issues for MacOS (M1):
- https://github.com/redhat-developer/odo/issues/5929
- https://github.com/redhat-developer/odo/issues/6012

/close
