### ISSUE TITLE
'odo' community enablement

### ISSUE THREAD

**Issue by slemeur** [redhat-developer/odo#332]
## Description
`odo` developer CLI for OpenShift is reaching the state where it could be used by end-user. We want to enable the community to start using `odo` and provide feedback about their developer experience on OpenShift using `odo`. 

We should be ready to welcome the community on the project, from both using and contributing aspects. For that we should be building a simple webpage for the project as well as revamping the readme.md. We should be providing links to online tutorials, examples and getting started guides.

## Tasks
- [ ] Revamp readme.md to include demo video, links to online tutorials, documentation and website
- [ ] 'odo' project page (similar to the one done for kedge) 
- [ ] Documentation for each commands
- [ ] Examples and Getting Started
- [ ] Setup public communication channel

**Comment by cdrage** [comment]
I'm going to split this off into a few different issues. a few tasks have already been completed:

- [ ] Revamp readme.md to include demo video, links to online tutorials, documentation and website
- [x] 'odo' project page (similar to the one done for kedge)
- [ ] Documentation for each commands, issue: https://github.com/redhat-developer/odo/issues/446
- [x] Examples and Getting Started
- [ ] Setup public communication channel

**Comment by cdrage** [comment]
Do you think that issue: 

Revamp readme.md to include demo video, links to online tutorials, documentation and website 

Is completed since we have the Katacoda tutorial, user-guide documentation as well as the website on the README.md, or should we include a demo video too?

@kadel @slemeur

**Comment by kadel** [comment]
It would be great to have quick start as a gif animation in readme. For example I really like what Origin has in the readme - https://github.com/openshift/origin

**Comment by cdrage** [comment]
@kadel Only thing left to do now is to create a gif (preferably using https://asciinema.org/) and put it on the README.
