### ISSUE TITLE
Migration to IBM Cloud

### ISSUE THREAD

**Issue by rnapoles-rh** [redhat-developer/odo#4800]
/kind user-story

## User Story
As a developer and tester I want to run tests in the IBM Cloud So that we can get a stable and reliably test framework

## Acceptance Criteria 

- [x] Get onboarded as admin
- [x] Create prerequisites for cluster creation (VPCs, cloud storage, subnets)
- [x] Create 4.7 Cluster
- [-] Create 3.11 Cluster > No longer required as we are dropping support for 3.11
- [x] Create Kubernetes cluster
- [x] Create service account (robot account) for kubeadmin > #4920 
- [x] Create service account (robot account) for developer > #4920 
- [x] Run tests manually on 4.7 cluster running in IBM Cloud (from laptop)
- [x] Run tests manually on 4.7 cluster running in IBM Cloud (from PSI VM)
- [x] Run test manually on kubernetes cluster running in IBM Cloud (from laptop and from Linux VM in PSI) (#4798)
- [x] Send invites to team members to get them onboarded as users and admins (where applicable)

## Links 
- Related Epic (mandatory): 

/kind user-story

**Comment by rnapoles-rh** [comment]
Ran Integration tests locally targeting the 4.7 cluster in IBM Cloud using Kubeadmin equivalent
Need to create a token and customize access to equivalent of developer account

**Comment by dharmit** [comment]
@rnapoles-rh we no longer need to bring up 3.11 cluster using minishift or otherwise. It's not supported any more, so odo doesn't support it.

**Comment by dharmit** [comment]
We need to move the odo-init image tests to IBM Cloud infra as well. PTAL https://github.com/openshift/odo/issues/4315.

**Comment by rnapoles-rh** [comment]
When using service accounts api-tokens, the clusters identifies the user as anonymous and does not allow any actions.
I will create full user accounts (not service accounts) for dev and admin users

**Comment by prietyc123** [comment]
@rnapoles-rh I think migration to IBM cloud includes some more tasks like:

- [ ] https://github.com/openshift/odo/issues/4897
- [ ] https://github.com/openshift/odo/issues/4896
Feel free to remove if I added something irrelavant.

**Comment by rnapoles-rh** [comment]
Already using IBM Pipelines and Linux / Windows Instances
