### ISSUE TITLE
IBM Cloud - Use Windows VMs in IBM Cloud to execute automated tests for PRs

### ISSUE THREAD

**Issue by rnapoles-rh** [redhat-developer/odo#4990]
/kind task

## Task
Create / update scripts to use Windows VMs in the IBM Cloud to execute automated tests

## Acceptance Criteria 
- [ ] Automated tests are executed in Windows VMs hosted in the IBM Cloud

## Links

**Comment by anandrkskd** [comment]
Scope of this issue:

- [ ] Create a windows VM on Ibm cloud 
- [ ] Setup VM 
       - [ ] Install and configure cygwin(if necessary), setup golang , other required software
 - [ ] Create nodessh file for VM
 - [ ] Use IBMCloud windows VM on jenkins for unit test and e2e-integration-test

**Comment by anandrkskd** [comment]
This issue is no longer valid as we are moving towards IBM cloud pipeline.
Hence, closing this issue.
/close
