### ISSUE TITLE
New odo testing system

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#5162]
We need to get into the point where we have tests running for each PR and also periodic/nightly jobs.

### Jobs executed for each PR
The PR tests should verify that the code that is about to get merge works.
All PR tests are executed on IBM Cloud, and OCP cluster can be of any stable version.

 - [x] unit tests started on linux (previw on https://github.com/feloy/odo/pull/7)
 - [x] unit tests started on windows
 - [ ] unit tests started  on mac - tracked with #5301 
 - [ ] integrations test executed from mac against OCP cluster - tracked with #5301 
 - [x] integrations test executed from windows against OCP cluster
 - [x] integrations test executed from linux against OCP cluster (preview on https://github.com/feloy/odo/pull/7)
 - [x] integrations tests executed from linux against the latest stable kubernetes cluster (can be minikube) (preview on https://github.com/feloy/odo/pull/7)

### The periodic/nightly jobs
Jobs should verify that what is in odo main branch works with all supported OCP versions.
All nightly jobs are executed using OpenShift CI (Prow)

- [x] integrations tests executed from linux against all supported OCP versions (usually the latest one and 2 previous versions)
- [x] integrations tests executed from linux against future OCP version (passing is optional)

/kind test
/area infra

**Comment by rnapoles-rh** [comment]
Tracking the MacOS portion with #5301
