### ISSUE TITLE
odo v3-alpha1

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#5312]
- Once even a single flag is provided it runs in non-interactive mode. All required information needs to be provided via flags
- If the command is executed without flags it can enter interactive mode
- every command should have `-o` flag to specify output format, and every command should support `-o json`

### CLI structure for v3.0.0-alpha1

- **`odo login`**
  - [x] as it is in v2
- **`odo logout`**
  - [x] as it is in v2
- **`odo init`**
  - [x] #5297
  - [x] #5470  
  - [x] #5408
- **`odo dev`** 
  - [x] #5299
- **`odo deploy`** 
  - [x] #5298
- **`odo preference`** 
  - [x] #5402
- **`odo build`**
  -  **`image`**
     - [x] as it is in v2
- **`odo list`**
  - [x] #5405
- **`odo delete`**
  - **`component`**
    - [x] #5409 
- **`odo version`**
  - [x] as it is in v2 
- **`odo utils`**
  - [x] as it is in v2

opened as PR https://github.com/redhat-developer/odo/pull/5341 for easier collaboration and review

**Comment by dharmit** [comment]
> `odo component` every command from “odo component *” already exists as a root command.

What should we replace the word `component` with in the commands `odo catalog list components` and `odo catalog describe component`?

**Comment by kadel** [comment]
> What should we replace the word `component` with in the commands `odo catalog list components` and `odo catalog describe component`?

Not sure yet, but it might actually stay as `component` there

**Comment by valaparthvi** [comment]
@kadel Do you want to do the honors of closing this epic, or will that be done after v3-alpha1 is released?

**Comment by kadel** [comment]
it is done, we can close it
/close
