### ISSUE TITLE
More documentation on Service Binding Operator and that it is optional

### ISSUE THREAD

**Issue by cdrage** [redhat-developer/odo#5395]
/kind documentation

## What mistake did you find / what is missing in the documentation?

I couldn't find any relevant information that indicates that Service Binding Operator is actually an OPTIONAL install and that we have code implemented that can link without the need of SBO.

## What is the relevance of it?

We should document this as well as have links to the code and information on SBO and why it is explicitly there / needed for installation. 

## TODO

- [ ] We should explain that Service Binding Operator is OPTIONAL. And is meant for persistency / using other tools other than odo after deploying
- [ ] Explain what it actually does
- [ ] Update documentation to indicate the above
