### ISSUE TITLE
odo v3-beta1

### ISSUE THREAD

**Issue by serenamarie125** [redhat-developer/odo#5522]
## New and updated commands in v3.0.0-beta2

- **`odo registry`** (with `--filter`, `--devfile`, `--devfile-registry`, `--details` flags)
  - [x] https://github.com/redhat-developer/odo/issues/5524
- **`odo create/delete/list/set namespace`** (and `odo create/delete/list/set project`)
  - [x] https://github.com/redhat-developer/odo/issues/5525
- **`odo logs`** and flag for `odo dev` to show logs
  - [ ] https://github.com/redhat-developer/odo/issues/5533
     - [x] https://github.com/redhat-developer/odo/issues/5622 
     - [x] https://github.com/redhat-developer/odo/issues/5715
     - [ ] https://github.com/redhat-developer/odo/issues/5716
- **`odo preference set/unset/add/remove/view`**
  - [x] https://github.com/redhat-developer/odo/issues/5535
- **`odo dev --no-watch`**
  - [x] https://github.com/redhat-developer/odo/issues/5631 
- **`odo dev --debug`**
  - [x] https://github.com/redhat-developer/odo/issues/5583
- **`odo add/list/describe/remove binding`**
  - [x] https://github.com/redhat-developer/odo/issues/5607 
    - [x] #5627
    - [x] #5635
    - [x] #5659
    - [x] #5693
- **`odo describe component`**
  - [x] https://github.com/redhat-developer/odo/issues/5661
- **`odo alizer -o json`**
  - [x] #5642
- **`odo list -o json`**
  - [x] #5643
- **`odo registry -o json`**
  - [x] #5644
- **`odo describe component -o json`**
  - [x] #5660 
- **`odo init -o json`**
  - [x] #5645

**Comment by dharmit** [comment]
@serenamarie125 @kadel I know that we haven't adhered to the `odo <verb> <noun>` pattern till v2. Are we consciously keeping things loose when it comes to odo in that we do have `odo create/delete/list`, but we will _also_ have `odo registry/catalog`? I'm not asking this as a critical remark, but more to understand if we want to consider `odo <verb> <noun>` during v3 or scrap that idea completely for odo.

**Comment by kadel** [comment]
We should still try to keep `verb noun` pattern where it makes sense. We definitely don't want to scapt that idea.  But there are areas where it is hard to keep this pattern, and  trying to force some constructs into `verb nount` pattern would be creating more confusion than if we break that pattern.

**Comment by kadel** [comment]
/close

two remaining items will be address separately 
https://github.com/redhat-developer/odo/issues/5607
https://github.com/redhat-developer/odo/issues/5727
