### ISSUE TITLE
Show component logs

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#5533]
## User Story
- As an odo user
- I want to be able to get logs (stdout and stderr) of the running component
- So that I can see if my application is running properly

## Acceptance Criteria
- [x] https://github.com/redhat-developer/odo/issues/5622  (users should be able to use `odo logs` command to display stdout and stderr logs of components deployed in dev and deploy mode.)
- [x] #5715
- [x] #5716
- [x] commands need to be able to handle multiple deployments, pods, and containers (For example devfile can contain multiple Deployments in outer-loop or there can be multiple containers in inner loop etc... )

/kind user-story

**Comment by dharmit** [comment]
We could make use of [`odo log` command from the `v2`](https://github.com/redhat-developer/odo/blob/v2/pkg/odo/cli/component/log.go) branch. 

It has its own handling of `Ctrl+c` which might need tweaking to work well with `odo dev` and Telemetry.

Also need to consider if user wants to see logs for run command or debug command. Although this is relevant only for inner loop. Maybe odo should figure this out by itself and act accordingly?

>  commands need to be able to handle multiple deployments, pods, and containers (For example devfile can contain multiple Deployments in outer-loop or there can be multiple containers in inner loop etc... )

Commands needed for this:

- [ ] `odo deploy --show-log --deployment <deployment-name> --pod <pod-name> --container <container-name>`
- [ ] `odo dev --show-log --container <container-name>`

For a devfile with both inner loop and outer loop resources, things could get a bit tricky. `odo logs` command would need more flags in that case:
- [ ] `odo logs --inner-loop` / `odo logs -i`
- [ ] `odo logs --outer-loop` / `odo logs -o` (using only `-o` could confuse it with "output" which `-o` is generally used for in `kubectl`, `wget`, `curl`)
- [ ] Consider the scenario of having multiple deployments/pods/containers as in above section.

odo should assume that there's only one deployment/pod/container if the user passes no flags.

**Comment by kadel** [comment]
## first part
- [ ] `odo logs` show ALL logs (both dev mode and deploy mode, from all containers)
- [ ] `odo logs --dev` shows logs of all containers running in dev mode
- [ ] `odo logs --deploy` show logs of all containers from deploy mode
- [ ] each log line should be prefixed with name of the container

**Comment by rm3l** [comment]
Closing this epic, since the last remaining piece (https://github.com/redhat-developer/odo/issues/5716) has just been merged.

/close
