### ISSUE TITLE
odo preference - cleanup

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#5535]
there should be the following set of subcommands for `odo preference` command

- [x] `odo preference set` - sets value for single value item (`UpdateNotification`, `Timeout`, `PushTimeout`, `RegistryCacheTime`, `Ephemeral`, `ConsentTelemetry`) (#5822 )
- [x] `odo preference unset` - unsets value (restores it to default) for single value item (`UpdateNotification`, `Timeout`, `PushTimeout`, `RegistryCacheTime`, `Ephemeral`, `ConsentTelemetry`) (#5822 )
- [x] `odo preference add` - adds value to array items (`registry`) (#5873 )
- [x] `odo preference remove` - removes value from array items (`registry`) (#5873 )
- [x] `odo preference view` -  view all preferences, and move `registry list` to `view` (#5850)
- [x] review name of the preference items, if needed rename it  and add description (#5822 )
- [x] Drop odo preference registry update; if needed, user can always remove and add registry (#5853)
## examples 
```
$ odo preference set ConsentTelemetry true

Value of 'ConsentTelemetry' preference was set to 'true'
```

```
$ odo preference unset ConsentTelemetry

Value of 'ConsentTelemetry' was removed from preferences. Its default value will be used.
```

```
$ odo preference add registry StagingRegistry https://registry.stage.devfile.io```

New Devfile registry was added to odo.
```

```
$ odo preference remove registry StagingRegistry

Devfile registry 'StagingRegistry' was removed from odo.
```

```
$ odo preference view

Preference parameters:
PARAMETER             VALUE
UpdateNotification    true (default)
Timeout               
PushTimeout           
RegistryCacheTime     
Ephemeral             
ConsentTelemetry      false


Devfile registries:
NAME                       URL                                   
StagingRegistry            https://registry.stage.devfile.io     
DefaultDevfileRegistry     https://registry.devfile.io           
``

**Comment by dharmit** [comment]
> [ ] `odo preference set` - sets value for single value item (`UpdateNotification`, `Timeout`, `PushTimeout`, `RegistryCacheTime`, `Ephemeral`, `ConsentTelemetry`)

We have been using `int` for all timeouts so far. I suggest using `time.Duration` for it. We can use `DurationVar` instead of `IntVar` from cobra point of view. Two benefits that I can think of by doing this:
* Not having to convert `int` to `time.Duration` as the values are now in `time.Duration` by default. 
* Clearer CLI documentation, IMO. For example, `odo watch -h` from main branch looks like:
    ```sh
    $ odo watch -h
    ....
    --delay int              Time in seconds blah blah blah (default 1)
    ....
    ```
    But with `--delay` being set to `DurationVar`, here it is:
    ```sh
    $ odo watch -h
    ....
    --delay duration         Time in seconds blah blah blah (default 1s)
    ....
    ```

**Comment by dharmit** [comment]
@valaparthvi yeah, that looks more like what I had in mind. 👍🏾

**Comment by valaparthvi** [comment]
@kadel What plans do you have for `odo preference registry list`, and `odo preference registry update`? Will we still keep them as is and only move add, and remove?

**Comment by valaparthvi** [comment]
> @kadel What plans do you have for `odo preference registry list`, and `odo preference registry update`? Will we still keep them as is and only move add, and remove?

From the cabal discussion:
- Drop `odo preference registry update`; if needed, user can always remove and add registry
- Move `odo preference registry list` to `odo preference view`
