### ISSUE TITLE
`odo add binding` should be able to list service instances from other namespaces

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#5820]
## User Story
- As an odo user
- I want to be able to bind services that are in a different namespace than my application
- So that I can for example share services that are shared between multiple applications or developers.

## Acceptance Criteria
- [x] first question in `odo add binding` is:
  "Do you want to list services from":
  - current namespace
  - all accessible namespaces  
- [x] When `odo add binding` lists service instances it should look beyond just the current namespace. It should check for bindable instances in all namespaces where users can list resources from.
- [x] If a service from other than the current namespace is selected the generated `ServiceBinding` should specify the namespace in the service section
```yaml
        services:
        - group: postgres-operator.crunchydata.com
          id: my-java-springboot-app-hippo
          kind: PostgresCluster
          name: hippo
          namespace: db
          resource: postgresclusters
          version: v1beta1
```
- [x] if service instance from the current namespace is selected it `namespace` should not be specified in `ServiceBinding` definition
