### ISSUE TITLE
Better default for component name (`odo init`/`odo dev`)

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#5847]
/kind user-story

## User Story
As an odo user working Java or NodeJS project I've already defined my project name in pom.xml or package.json file
I want odo to suggest a default name that is based on the name that I already defined.
So that I don't have to type it again.

This is about `? Enter component name:` question in initial flow in `odo init` and `odo dev`

## Acceptance Criteria 
- [ ] if `package.json` exists the suggested default component name should be value of the `name` field from `package.json`;
- [ ] if `pom.xml` exists the suggested default component name should be value of the `artifactId` field from `pom.xml`
- [ ] if non of the previous rules was applied use the name of the current directory as a default component name. 
- [ ] in all cases the name needs to be sanitized to make sure that it is always valid based on the allowed format for  devfile's `metadata.name` 

/priority medium

/kind user-story

**Comment by kadel** [comment]
/status blocked
https://github.com/redhat-developer/alizer/issues/96

**Comment by valaparthvi** [comment]
> redhat-developer/alizer#96

Issue resolved.
