### ISSUE TITLE
[EPIC] Address users feedback

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#5848]
- [ ] https://github.com/redhat-developer/odo/issues/5728
- [ ] https://github.com/redhat-developer/odo/issues/5819
- [ ] https://github.com/redhat-developer/odo/issues/5847

**Comment by kadel** [comment]
Closing this as most of the items were addressed last remaining item is https://github.com/redhat-developer/odo/issues/5862 but based on the information from user requesting this it might not be a priority. 

/close
