### ISSUE TITLE
[Epic] Use odo with Podman (without Kubernetes/OpenShift cluster) [stage 1]

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#5871]
# Core user story

As an odo user, I want to be able to run my development environment locally without requiring kubernetes/openshift cluster
So that:
- I don't need to run the cluster locally and save resources
- I get a quick response (quicker than when using cluster)

tasks/sub-user stories (this track issues that need to be resolved before we can move podman out of the experimental mode):

- [x] https://github.com/redhat-developer/odo/issues/5865
- [x] https://github.com/redhat-developer/odo/issues/6159
- [x] https://github.com/redhat-developer/odo/issues/6162
- [x] https://github.com/redhat-developer/odo/issues/6160
- [x] https://github.com/redhat-developer/odo/issues/6186
- [x] https://github.com/redhat-developer/odo/issues/6185
- [x] https://github.com/redhat-developer/odo/issues/6250
- [x] https://github.com/redhat-developer/odo/issues/6150
- [x] https://github.com/redhat-developer/odo/issues/6149
- [x] https://github.com/redhat-developer/odo/issues/6200
- [x] https://github.com/redhat-developer/odo/issues/6151
- [x] #6317
- [x] #6330
  - **NOTE**: For now, a PVC is always created. Reminder to generate `EmptyDir` volumes when `Ephemeral` preference is true (https://github.com/redhat-developer/odo/pull/6328#pullrequestreview-1191676898)
- [x] #6335
- [x] #6296
- [x] #6299
- [x] https://github.com/redhat-developer/odo/issues/6236
- [x] #6318
- [x] https://github.com/redhat-developer/odo/issues/6333
- [x] #6297
- [x] #6298
- [x] #6336
- [x] #6416
- [x] https://github.com/redhat-developer/odo/issues/6434
- [x] https://github.com/redhat-developer/odo/issues/6459

Continuing of this epic (stage 2) is https://github.com/redhat-developer/odo/issues/6578

**Comment by valaparthvi** [comment]
/close
Closing this issue since we've covered all the ACs. Moved #6510 to Stage 2.
