### ISSUE TITLE
[EPIC] Support IDE plugins updating to v3

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#5994]
- [x] https://github.com/redhat-developer/odo/issues/5996
- [x] https://github.com/redhat-developer/odo/issues/5997
- [x] https://github.com/redhat-developer/odo/issues/5990

**Comment by kadel** [comment]
OpenShift toolkit and IntelliJ plugins are now using v3
/close
