### ISSUE TITLE
Automate command output in docs

### ISSUE THREAD

**Issue by valaparthvi** [redhat-developer/odo#6192]
/area documentation
/kind epic

## What mistake did you find / what is missing in the documentation / what is the relevance of it?

1. Store the current output for all the commands in separate mdx files.
2. Write integration/unit tests comparing the real time output of a command with the one stored in the mdx files.
3. If the test fails, it means that we need to update the output in mdx files.
4. The tests will be run in the CI for every PR.

For reference - https://www.youtube.com/watch?v=AQDILnknTJ0&list=PLUJzERpatfsWYhMH0NOjSXemQh5Tu9g1W&index=32&t=3s (it is in french)

### Acceptance Criteria
- [x] #6517
- [ ] Every command output should be put inside a docs-mdx/<name>.mdx file. 
- [ ] Command Reference
    - [ ] odo dev
    - [x] odo init (#6442)
    - [ ] odo preference view
    - [ ] odo add binding
    - [ ] odo remove binding
    - [x] #6675
    - [x] odo delete namespace #6724 
    - [ ] odo build-images
    - [ ] odo list
    - [ ] odo list namespace #6724 
    - [ ] odo list component
    - [ ] odo list binding
    - [ ] odo deploy
    - [ ] odo describe binding
    - [ ] odo describe component
    - [ ] odo logs
    - [ ] odo set namespace #6724 
    - [ ] odo registry 
- [ ] User Guides
    - [x] Quickstart (WIP)
    - [ ] Test Quickstart guides on Podman
    - [ ] Advanced Guide
    - [ ] Connecting to a service
    - [ ] Experimental Mode

Example PR: #6442

**Comment by valaparthvi** [comment]
> LGTM. I agree there is a lot of repetitive data, but since the Devfiles are quite different, it might be hard to factorize, IMO. Not an expert with MDX / JSX stuff, but there might be some room for reusability. So I am not sure it would be worth spending time right now trying to optimize this.
> 
> However, this makes me think of 2 things:
> 
> * Based on a recent discussion, maybe we could use each of those Devfiles as input in E2E tests, and import them as is in these docs. This way, we would be able to test them as well. And for line highlighting in the Docs, I can imagine some generic MDX Component accepting the path to the Devfile along with line numbers as input properties, so as to keep highlighting the relevant lines.
> 
> * These Advanced Guides could be simplified further now that we support parsing multi-document YAML in a single K8s component (#6372)
> 
> 
> But that's another story that can be handled in separate PRs.

https://github.com/redhat-developer/odo/pull/6388#pullrequestreview-1209842454

**Comment by rm3l** [comment]
As discussed, this low-priority item (from the 2023Q1 goal) has been moved back into the backlog.
