### ISSUE TITLE
Compatibility with DevSpaces devfiles. 

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#6478]
## User Story
- As an odo user
- I want to be able to use a project with devfile that was originally created for DevSpaces
- So that I can work on the same project with my teammates using DevSpaces without modifying devfile.yaml

## Acceptance Criteria
- [ ] Devfiles that are compliant with spec and work with DevSpaces should work with odo as well 
- [ ] It should be possible to use devfile with no default build or run defined
- [ ] There should be a command that allows manually executed any command-defined devfile (for example `odo run <command_name>`) (https://github.com/redhat-developer/odo/issues/6568)

Related stories:
- https://github.com/redhat-developer/odo/issues/6549
- https://github.com/redhat-developer/odo/issues/6568
- https://github.com/redhat-developer/odo/issues/6569

/kind user-story
/priority medium

**Comment by rm3l** [comment]
/close

All items completed.
