### ISSUE TITLE
`odo run <devfile-command>` when `odo dev` is running

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#6568]
/kind user-story

## User Story
As an odo user, I want to be able to start commands defined in the devfile when I need to So that I can run actions defined in the devfile, like, for example, running commands that test things, or nondefault build commands that do some optional extra work.

This will allow users to follow the same workflow as in IDEs and DevSpaces where the command are usually executed only upon user request.

## Acceptance Criteria 
- [ ] there should be a command (`odo run` for example) that takes one argument that is the command name and executes the command defined in devfile
- [ ] `odo run` assumes that `odo dev` is running in a separate terminal, if `odo dev` is not running (resources not present on the cluster) `odo run` errors out and tells the user to run `odo dev` first. 
- [ ] if the command is `exec` command and the container where the program needs to be started is not running, the command should be executed as a `Job`; for podman this can be running inside a pod/container.
- [ ] if the command is `exec` and the container is already running, it should be just executed inside the running container
- [ ] if command is `apply` it just applies what it needs to :-) `kubernetes`/`openshift` components get created, `container` component gets turned into `Deployment` is `dedicatedPod: true`
- [ ] if command is `composite` that it performs all action based on the above rules
- [ ] `odo run` streams logs into the terminal and waits for the command to finish.
- [ ] user can interrupt the command by pressing  control-c; cleanup the resources. 
- [ ] the exit code of `odo run` command reflect the exit code of the last devfile command executed. If the last command was `apply` and it was successful it returns 0, if failed returns 1
- [ ] Because odo dev is running, if Kubernetes/OpenShift resources are created with Apply commands, they should be deployed in "Dev" mode (to be cleanup when odo dev terminates) - make it clear it will be cleaned up.

## Links 

This will enable the implementation of  https://github.com/redhat-developer/odo/issues/6070

related to https://github.com/redhat-developer/odo/issues/6478 epic

/kind user-story
/priority medium

**Comment by rm3l** [comment]
/triage needs-information
/assign @kadel 

Add more details

**Comment by valaparthvi** [comment]
**[Grooming Call April 6, 2023]**
- Implement this with command-first approach.
- `odo run` running a long running command should terminate if the `odo dev` pod restarts.
- Refactor the command handlers to be more generic. Design a new architecture. [To be handled in a separate issue].
- Implement `odo run` with the new architecture.
- Interactive mode to be added at a later stage.
- Once the new arch has been implemented, modify `odo dev` and `odo deploy` to use it, as a last stage.

@kadel to add about the long term vision of implementing this issue.

- `odo dev` can run without any default commands.
- Create the second phase of this issue (?)

**Comment by feloy** [comment]
It seems we will have to introduce flags similar to `Docker exec`' and `kubectl exec`'s `-i` (`stdin`) and `-t` (`--tty`), to give the user the possibility to set the terminal in raw mode or not, depending on the expectations.

- In raw mode, stdout and stderr are both mixed in stdout
- In raw mode, Ctrl-c is passed inside stdin, and the distant process receives it and is interrupted
- In raw mode, the execution fails if stdin is not a terminal (integration tests)

**Comment by feloy** [comment]
> It seems we will have to introduce flags similar to `Docker exec`' and `kubectl exec`'s `-i` (`stdin`) and `-t` (`--tty`), to give the user the possibility to set the terminal in raw mode or not, depending on the expectations.
> 
> * In raw mode, stdout and stderr are both mixed in stdout
> * In raw mode, Ctrl-c is passed inside stdin, and the distant process receives it and is interrupted
> * In raw mode, the execution fails if stdin is not a terminal (integration tests)

I have implemented it to detcted if stdin/out are a terminal. The raw mode will be set only if they are.
