### ISSUE TITLE
[Epic] Use odo with Podman (without Kubernetes/OpenShift cluster) [stage 2]

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#6578]
This is list of the issues related to podman that can be addressed after podman is moved out of the experimental mode.

Notes (for when this feature will be out of experimental mode):
- [ ] https://github.com/redhat-developer/odo/issues/6331
- [ ] #6424
- [ ] https://github.com/redhat-developer/odo/issues/6458
- [ ] https://github.com/redhat-developer/odo/issues/6488
- [x] https://github.com/redhat-developer/odo/issues/6492
- [ ] https://github.com/redhat-developer/odo/issues/6493
