### ISSUE TITLE
Odo should work with OpenShift and Kubernetes clustrer provided by cloud providers

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#6739]
/kind user-story

## User Story
As an odo user, I want to be able to use odo with clusters created in cloud.

## Acceptance Criteria 
- [x] `odo dev` should work with ROSA (Red Hat OpenShift Service on AWS) @kadel tested it and it works without any problems
- [x] `odo dev` should work with ARO (Microsoft Azure Red Hat OpenShift) @kadel tested it and it works without any problems
- [x] `odo dev` should work with OpenShift on GCP
- [x] `odo dev` should work with AKS (Azure Kubernetes Service) https://github.com/redhat-developer/odo/issues/6585
- [x] `odo dev` should work with AWS EKS (Elastic Kubernetes Service) https://github.com/redhat-developer/odo/issues/6588
- [x] `odo dev` should work with GKE (Google Kubernetes Engine) https://github.com/redhat-developer/odo/issues/6706

/kind user-story
/kind epic
