### ISSUE TITLE
[Epic] Use odo with Podman (without Kubernetes/OpenShift cluster) [stage 3]

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#6841]
continuing of #6578 

**Bugs**
- [x] https://github.com/redhat-developer/odo/issues/6956
- [x] https://github.com/redhat-developer/odo/issues/6824

**Documentation**
- [x] https://github.com/redhat-developer/odo/issues/6794
- [x] https://github.com/redhat-developer/odo/issues/6858
- [x] https://github.com/redhat-developer/odo/issues/6859
- [x] https://github.com/redhat-developer/odo/issues/6860
- [x] https://github.com/redhat-developer/odo/issues/6862

Stage 4 (for later): https://github.com/redhat-developer/odo/issues/6991

**Comment by rm3l** [comment]
Closing this epic as all issues (doc + bugs) in it have been completed.

/close
