### ISSUE TITLE
[Epic/ODO-93] Integrate devfile.odo.dev website into odo

### ISSUE THREAD

**Issue by rm3l** [redhat-developer/odo#6895]
/kind epic

Copied from ODO-93

> ## Problem statement
> 
> One of the biggest challenges for users is devfile customization to fit their project. 
> 
> ## Solution
> 
> We need to make customizing devfiles simpler, ideally to the point that users don’t have to deal with or understand devfiles.
> 
> We could try to create a Web UI that will abstract devfile structure to a better digestible form. This new form doesn’t have to; in fact, it should not resemble the devfile file structure.  
> 

---

## User Story
As an odo user, I want a better and simpler way to visualize and edit my local Devfile, So that I don't struggle with manually tailoring the Devfile to my project needs.

## Acceptance Criteria 
- [x] It should expose a Web UI integrated with `odo dev` and connected to the local Devfile for visualization and editing
- [x] It should not be hidden in experimental mode
- [x] API/web server should by started by default in `odo dev`
- [x] The output of the `odo dev` should show on which host an port the web interface and API is served

## Links 
- ODO-93

## Sub-stories / tasks
- [x] https://github.com/redhat-developer/odo/issues/6899
- [x] https://github.com/redhat-developer/odo/issues/6934
- [x] https://github.com/redhat-developer/odo/issues/6901
- [x] https://github.com/redhat-developer/odo/issues/6903
- [x] https://github.com/redhat-developer/odo/issues/6900
- [x] https://github.com/redhat-developer/odo/issues/6902
- [x] https://github.com/redhat-developer/odo/issues/6943
- [x] https://github.com/redhat-developer/odo/issues/6942
- [x] https://github.com/redhat-developer/odo/issues/6987
- [x] https://github.com/redhat-developer/odo/issues/6963

## Enhancements
- [x] #7018
- [x] #7019
- [x] #7020
- [x] #7021

## Bugs
- [x] #7022

/kind user-story

**Comment by rm3l** [comment]
**Grooming (2023-06-15)**

- Integrate @feloy's POC in odo: https://devfile.odo.dev/
- Integrate telemetry into that as well (enabled only if odo telemetry is enabled)
  - Current POC is a single page application => track what info people are modifying
- Website should use the API we are developing
- 1 website per dev session; so 2 dev sessions on different platforms might modify the same devfile. Look for a way to propagate changes.
- Experimental mode

Actions / Issues to create:
- Move PoC to odo and serve the static files (same port as API). Make it clear that parent is not supported yet.
- Move the state (stored currently in WebAssembly module) to odo. Modify the API endpoints to manipulate this state. Question: auto-save or not? (if the dev session is stopped but user had made changes to the Devfile via the website) => auto-save.
- Work on raw Devfile
- For the future: website as the console of odo dev (logs, controls to trigger sync, ...)
- Living chart with the current state

**Comment by rm3l** [comment]
/remove-triage needs-information

Issue groomed and broken down into smaller issues that we will consider sizing later.

**Comment by rm3l** [comment]
@kadel Per your recent update on this issue, I've created a specific task to track the last 3 acceptance criteria (to move the UI and API out of the experimental mode): https://github.com/redhat-developer/odo/issues/6963

**Comment by feloy** [comment]
All issues have been done
