### ISSUE TITLE
Simple `ocdev` installation/update/uninstallation

### ISSUE THREAD

**Issue by slemeur** [redhat-developer/odo#70]
### Goal
The goal of this epic is to provide a simple installation flow for `ocdev` as well as update and uninstallation. 
While the installation might not be difficult, we should make it really simple so the users could (ideally) install `ocdev` with a single instruction line. 

#### Getting Started
We need to think about the getting started experience of the end-user with `ocdev` and try to provide the best first experience. This implies a certain requirements on how the user can install `ocdev` as well as a flow in the documentation to help the user to quickly ramp up.

The installation of  `ocdev` is requiring some pre-requisites that we need to document. 

Once those pre-requisites are installed, we should be looking at how we can simplify the installation of `ocdev`. For example, on MacOS, we could be using homebrew packages, on Linux we could install from a single command line `wget -qO- https://github.com/redhat-developer/ocdev/master/blob/install-ocdev.sh | sh` . This should be properly documented too.

After having proceed of the installation, we should guide the user to verify that `ocdev` has been properly installed.

Now that `ocdev` is ready, we should provide a default basic set of first commands, something like:
- `oc login`
- `ocdev application create first-app`
- `ocdev component create nodejs`
- `ocdev ocdev component create --git https://github.com/openshift/nodejs-ex`
- `ocdev component push`

#### Staying up to date
How do we handle the updates of `ocdev` ? Could we be looking at different solutions so that `ocdev` keep itself automatically up to date?
To start, we can just put a warning to notify the user that there is a new version of `ocdev` available, and point to the installation/upgrade documentation.

#### Troubleshooting
What happens when the developer is hitting some issues? Can we provide different `DEBUG` information when interacting with the OpenShift API? 

#### Uninstallation
We need to provide a way for the developer to properly uninstall `ocdev`. 
If `ocdev` was installed with homebrew, we can have an uninstall command. 
We should provide proper set of instructions to delete on Linux and Windows too.

### Documentation
We should be providing documentation for installing `ocdev` to cover:
- Pre-requisities
- Download and Installing: MacOS, Windows, Linux
- Verify your installation
- Getting started
- Update `ocdev`cli
- Troubleshooting
- Uninstallation

### Sub Tasks
- [x] Create Homebrew package - https://github.com/redhat-developer/ocdev/issues/69
- [x] show warning when user is running older ocdev version -  https://github.com/redhat-developer/ocdev/issues/71
- [x] Create installation bash script #74
- [x] add proper documentation #75
- [ ] 
- [ ] 
- [ ]

**Comment by pradeepto** [comment]
@slemeur Other than homebrew what else do we want? As in for other platforms?

**Comment by slemeur** [comment]
You mentioned https://chocolatey.org/ for Windows. That could be nice.

**Comment by cdrage** [comment]
@slemeur Can we close this? I believe we have all the relevant docs now.

**Comment by cdrage** [comment]
Hey @slemeur I'm going to close this for now to cut-down on our issues and I believe this is fully covered :+1: Let us know if it's not! (specifically uninstall documents, I'm not too sure what you mean other than removing just the binary)
