### ISSUE TITLE
[Epic] Web UI as main odo interface

### ISSUE THREAD

**Issue by kadel** [redhat-developer/odo#7002]
/kind epic

## User Story
As an odo user I want to be able to use Web UI for all my interactions with odo as it provides a much nicer UI and better UX than the command line. 

Commandline is still important as some action can be done quicker using CLI, and also I can use it for scripting.

## Acceptance Criteria 
- [ ] in web ui user should be able to see all components deployed in on the cluster using and in what mode they are (dev/deploy)
- [ ] User should be able to run `odo` with UI interface in a directory without `devfile.yaml` file.
- [ ] User should be able to add component folders (folders with devfile.yaml) into the workspace. Workspace is the set of components that the user can interact with using UI.
- [ ]
