### ISSUE TITLE
Backstage Golden Path Template (GPT) for `odo init`

### ISSUE THREAD

**Issue by rm3l** [redhat-developer/odo#7114]
/kind epic
/area backstage

As a Backstage admin administrating a given Backstage instance for my organization, I would like to have an example of a golden path template allowing users to create an example of an application with a Devfile that they could further customize as needed.

This is a follow-up to https://github.com/redhat-developer/odo/issues/7086 spike story.

### Acceptance Criteria
- [ ] It should provide a Golden Path Template that executes `odo init` to create an example application from selected devfile and starter project

### Sub-stories
- [ ] Implement Devfile Selector Custom Field Extension for Backstage
- [ ] Implement Backstage Custom Action for `odo init`
- [ ] Implement `odo init` example Golden Path Template

### Related Epics
- https://github.com/redhat-developer/odo/issues/7091

**Comment by rm3l** [comment]
Marking this as complete. I created an example of Backstage GPT relying on the [Devfile Selector custom field extension](https://github.com/redhat-developer/odo/issues/7115) and the [custom action plugin](https://github.com/redhat-developer/odo/issues/7116), and which calls `odo init` to generate a starter project, which is then published to a GitHub repo and registered into the Backstage Catalog.

For now, this is available as a POC under my personal GH account: https://github.com/rm3l/odo-backstage-golden-path-template/blob/main/README.md

We'll create additional issues based on the next steps about this.

Remaining things to do:
- [ ] Move this away from my personal account?

/close
